sudo: required
services:
  - docker

before_install:
  - docker build -t faustaleonardo/multi-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true faustaleonardo/multi-client npm test

after_success:
  - docker build -t faustaleonardo/multi-client ./client
  - docker build -t faustaleonardo/multi-server ./server
  - docker build -t faustaleonardo/multi-worker ./worker
  - docker build -t faustaleonardo/multi-nginx ./nginx
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push -t faustaleonardo/multi-client
  - docker push -t faustaleonardo/multi-server
  - docker push -t faustaleonardo/multi-worker
  - docker push -t faustaleonardo/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-681368228435
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
